apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  mongoUsername: {{ .Values.secrets.mongoUsername | b64enc | quote }}
  mongoPassword: {{ .Values.secrets.mongoPassword | b64enc | quote }}