apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  mongoUsername: {{ .Values.secrets.mongoUsername | quote }}
  mongoPassword: {{ .Values.secrets.mongoPassword | quote }}