apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  postgresUsername: {{ .Values.secrets.postgresUsername | quote }}
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}