apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  postgresUsername: {{ .Values.secrets.mongoUsername | quote }}
  postgresPassword: {{ .Values.secrets.mongoPassword | quote }}