eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/steam
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #flyway:
   # baseline-on-migrate: true
    #enabled: true
    #baseline-description: "init"
    #baseline-version: 0
    #user: ${spring.datasource.username}
    #password: ${spring.datasource.password}

springdoc:
  api-docs:
    path: /games/v3/api-docs
  swagger-ui:
    path: /games/swagger-ui.html

uploads:
  dir: UI_Spring/public/uploads/games
