eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_GAMES:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}


server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/steam}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #flyway:
   # baseline-on-migrate: true
    #enabled: true
    #baseline-description: "init"
    #baseline-version: 0
    #user: ${spring.datasource.username}
    #password: ${spring.datasource.password}

springdoc:
  api-docs:
    path: /games/v3/api-docs
  swagger-ui:
    path: /games/swagger-ui.html

uploads:
  dir: ${UPLOADS_GAMES_DIR:games-service/src/main/resources/static/uploads/games}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always