eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_GATEWAY:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always