eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_LIBRARY:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

spring:
  data:
    mongodb:
      username: ${MONGO_DB_USER:achraf}
      password: ${MONGO_DB_PASSWORD:ladhari02}
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: library
      authentication-database: admin
      auto-index-creation: true
springdoc:
  api-docs:
    path: /library/v3/api-docs
  swagger-ui:
    path: /library/swagger-ui.html

server:
  port: 8020

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
