eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_ORDER:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/steam}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    user-url: ${USER_URL:http://localhost:8222/api/v1/users}
    games-url: ${GAMES_URL:http://localhost:8222/api/v1/games}
    payment-url: ${PAYMENT_URL:http://localhost:8222/api/v1/payments}
    library-url: ${LIBRARY_URL:http://localhost:8222/api/v1/library}
springdoc:
  api-docs:
    path: /order/v3/api-docs
  swagger-ui:
    path: /order/swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
