eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_PAYMENT:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/steam}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    games-url: ${GAMES_URL:http://localhost:8222/api/v1/games}
springdoc:
  api-docs:
    path: /payment/v3/api-docs
  swagger-ui:
    path: /payment/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

