eureka:
  instance:
    hostname: config-server
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/steam
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    games-url: http://localhost:8222/api/v1/games
springdoc:
  api-docs:
    path: /payment/v3/api-docs
  swagger-ui:
    path: /payment/swagger-ui.html

