eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME_USER:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

uploads:
  dir: ${UPLOADS_USER_DIR:user-service/src/main/resources/static/uploads/user}

spring:
  data:
    mongodb:
      username: ${MONGO_DB_USER:achraf}
      password: ${MONGO_DB_PASSWORD:ladhari02}
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: users
      authentication-database: admin
      auto-index-creation: true

application:
  config:
    library-url: ${LIBRARY_URL:http://localhost:8222/api/v1/library}

springdoc:
  api-docs:
    path: /users/v3/api-docs
  swagger-ui:
    path: /users/swagger-ui.html

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
