apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: chrayef/client:57
        ports:
        - containerPort: 4200
        envFrom:
        - configMapRef:
            name: app-configmap