apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
      - name: games
        image: chrayef/games-service:41
        ports:
        - containerPort: 8070
        envFrom:
        - configMapRef:
            name: app-configmap
        env: 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgresUsername

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgresPassword