apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: chrayef/payment-service:41
        ports:
        - containerPort: 8050
        envFrom:
        - configMapRef:
            name: app-configmap
        env: 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgresUsername

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgresPassword