apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: chrayef/user-service:41
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: app-configmap
        env: 
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongoUsername

        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongoPassword