server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always